#This workflow will merge automatically when a pull request comes in. 

name: auto merge


on: 
  push: 
    branches: 
      [main, MaChwe-branch, cheskalazo-branch, jiaqibranch, laukwangweibranch, perlebranch]
  pull_request:
    branches: 
      [main, MaChwe-branch, cheskalazo-branch, jiaqibranch, laukwangweibranch, perlebranch]

    

jobs: 
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          labels: automerge

              
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge    
        uses: "pascalgn/automerge-action@v0.13.0"
        id: "automerge"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABEL_NAME: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
        with:
          pull-request: ${{ github.event.inputs.pull-request }}
          
  main:
    runs-on: ubuntu-latest
    steps: 
      - name: check for merge conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PR: Merge Conflict"
          removeOnDirtyLabel: "automerge"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, @ScrumMaster please resolve."
          commentOnClean: "Conflicts have been resolved. Automerge will proceed pull request shortly."
