##This workflow automatically labels Issues or PullRequests based on project card moves on the kanban board.
  
on:
  project_card:
    types: [created, moved]

name: Project Card Event

jobs:
  triage:
    name: Auto card labeler
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/auto-card-labeler@v1
    
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: jenschelkopf/project-card-moved-notification@1.0
