name: Discord Notifier for QA
on: 
  push:
    branches: [cheskalazo-branch, MaChwe-branch]
    
jobs:
  build:
    # build job
    runs-on: ubuntu-latest
    name: Build the Code
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Test the Code
      id: TestWithPytest
      run: | 
        pytest -v --junitxml=report.xml
    # test job
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
      #- test
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps: 
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'QA UPDATE'
          avatar-url: 'https://media-exp1.licdn.com/dms/image/C4E0BAQHdT7WU3uKGgA/company-logo_200_200/0/1519878893739?e=2159024400&v=beta&t=4S_xQekU7pBE8BKd_MWgcfIlEDD8chTabeGOjriHx_4'
          description: '${{ github.event_name }} trigged this {{STATUS}}!'
